# Ansible managed: /Users/souley/Documents/Projects/Waari_Project/waari_api/railsbox/ansible/roles/mysql/templates/database.yml.j2 modified on 2015-10-24 21:52:30 by souley on Souleymanes-MBP.home

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: waari

  username: vagrant
  password: vagrant

test:
  <<: *default
  database: waari_test
