# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 766635686d0b93b279e715faf399aa858e2ad5726778af116b40e8d6ebc26ac4913be2946ecae4bb4f849c00e99c62e92517b344e12fedb5bfede1315d44057b

test:
  secret_key_base: 9ee74a8abc375a55a8c7d0f9217738b807e949d24d08b05ae22b12cb203a219a7539d83ef4e50f52dde4e73e244d3581745297df911741e10fec4102af13c85e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
